### ISSUE TITLE
Integrations and platforms could not be set up

### ISSUE THREAD

**Issue by mrcfelici** [chomupashchuk/ariston-remotethermo-home-assistant-v2#75]
Invalid config reports after HA update to 2025.1.0
The integrations and platforms could not be set up

Logs:
Registratore: homeassistant.setup
Fonte: setup.py:334
Prima occorrenza: 10:22:13 (1 occorrenze)
Ultimo accesso: 10:22:13

Setup failed for custom integration 'ariston': Unable to import component: cannot import name 'DEVICE_CLASS_CONNECTIVITY' from 'homeassistant.components.binary_sensor' (/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ariston_v2/__init__.py", line 28, in <module>
    from .binary_sensor import binary_sensors_default
  File "/config/custom_components/ariston_v2/binary_sensor.py", line 5, in <module>
    from homeassistant.components.binary_sensor import (
    ...<3 lines>...
    )
ImportError: cannot import name 'DEVICE_CLASS_CONNECTIVITY' from 'homeassistant.components.binary_sensor' (/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ariston_v2/__init__.py", line 28, in <module>
    from .binary_sensor import binary_sensors_default
  File "/config/custom_components/ariston_v2/binary_sensor.py", line 5, in <module>
    from homeassistant.components.binary_sensor import (
    ...<3 lines>...
    )
ImportError: cannot import name 'DEVICE_CLASS_CONNECTIVITY' from 'homeassistant.components.binary_sensor' (/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py)

**Comment by baccro** [comment]
Good morning and Happy New Year! The same thing happens to me after the update 2025.1

**Comment by Salsalove** [comment]
same here...@chomupashchuk please, fix it!

**Comment by Ric199021** [comment]
I also have this problem but I've downgrade back to  Core 2024.12.5  and it's working. I'll wait few days to see if this can be fixable then I'll update it again. If not I'll find another solution.

**Comment by pico1881** [comment]
I hope @chomupashchuk is fine in Ukraine since it's been a while since he updated this integration.
I'm not an expert, but I tried to solve the incompatibilities of this integration with HA 2025.1.
At this link there is the fork where I fixed the problems and now it seems to work with HA 2025.1
https://github.com/pico1881/ariston-remotethermo-home-assistant-v2

**Comment by dcigir** [comment]
> I hope @chomupashchuk is fine in Ukraine since it's been a while since he updated this integration. I'm not an expert, but I tried to solve the incompatibilities of this integration with HA 2025.1. At this link there is the fork where I fixed the problems and now it seems to work with HA 2025.1 https://github.com/pico1881/ariston-remotethermo-home-assistant-v2

I can confirm it's working! Thank you :)

**Comment by Salsalove** [comment]
> I hope @chomupashchuk is fine in Ukraine since it's been a while since he updated this integration.
> 
> I'm not an expert, but I tried to solve the incompatibilities of this integration with HA 2025.1.
> 
> At this link there is the fork where I fixed the problems and now it seems to work with HA 2025.1
> 
> https://github.com/pico1881/ariston-remotethermo-home-assistant-v2

Thank you! It's working fine!

**Comment by Burnerface** [comment]
> J'espère@chomupashchukça va bien en Ukraine car ça fait un moment qu'il n'a pas mis à jour cette intégration. Je ne suis pas un expert, mais j'ai essayé de résoudre les incompatibilités de cette intégration avec HA 2025.1. Sur ce lien, il y a le fork où j'ai corrigé les problèmes et maintenant il semble fonctionner avec HA 2025.1 https://github.com/pico1881/ariston-remotethermo-home-assistant-v2

Super ! ça marche pour moi aussi !

**Comment by ivanuski9** [comment]
For version 2025.1.1 it still fails.

**Comment by pico1881** [comment]
> For version 2025.1.1 it still fails.

I updated to version 2025.1.1 and it works. Do you have any errors in the logs?

**Comment by baccro** [comment]
I updated to the 2025.1.1 version and replaced the entire Ariston folder in Custom_components with the changes of @pico1881 and I also confirm that it worked. Thank you.

**Comment by eacxx** [comment]
Excellent, my "not an expert" friend :)
I can confirm also that your fix is working in 2025.1.1
Thank you very much!

**Comment by ivanuski9** [comment]
Ok now it's working for me. I updated to the latest version.

**Comment by eacxx** [comment]
@ivanuski9 it's not so clear for me.
You just updated HA to the last version and the Ariston integration is working for you?
Or you want to say that the last HA version is working with our colleague's @pico1881 mod?

**Comment by ivanuski9** [comment]
I updated HA to the latest version and it doesn't work for me, but I reinstalled the ariston plugin and it started working. I haven't tried the pico1881 plugin yet.
